# Generated by Django 4.2.6 on 2023-10-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_tasks_images_taskimage_tasks_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='images',
        ),
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
