# Generated by Django 4.2.6 on 2023-10-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_tasks_images_delete_taskimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=30),
        ),
    ]
