# Generated by Django 4.2.6 on 2023-10-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Priority',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=30),
        ),
    ]
