# Generated by Django 4.2.6 on 2023-10-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=30),
        ),
    ]
