# Generated by Django 4.2.6 on 2023-10-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_tasks_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
