# Generated by Django 4.2.6 on 2023-10-11 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_tasks_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='images',
            field=models.ImageField(blank=True, default='None', upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaskImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='TaskImage')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks')),
            ],
        ),
    ]
