# Generated by Django 4.2.6 on 2023-10-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_tasks_images_taskimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='images',
        ),
    ]
